### ISSUE TITLE
[MAJOR] Mobile Support

### ISSUE THREAD

**Issue by TannerGhosen** [TannerGhosen/tannerghosen.github.io#2]
Need to add mobile support via CSS/jQuery.

**Comment by Tannerghosen** [comment]
11/15/17
#4 also now shares the same goal with #2, both of need to be working.

**Comment by Tannerghosen** [comment]
Beta Release of Mobile Support

**Comment by Tannerghosen** [comment]
Further updates after Christmas.

**Comment by TannerGhosen** [comment]
Disappointing news - I've decided to use a third party code to aid with this, despite my intentions to do it from scratch. I am utilize mobile-detect.js (https://github.com/hgoebl/mobile-detect.js) by @hgoebl.
